### ISSUE TITLE
Ip & Port Change Via Variable

### ISSUE THREAD

**Issue by satishkrr** [getnamo/udp-ue4#14]
Hi is it possible to change the ip and port by sending it as parameters

**Comment by getnamo** [comment]
Both open send socket (https://github.com/getnamo/udp-ue4/blob/master/Source/UDPWrapper/Public/UDPComponent.h#L139) and open receive socket (https://github.com/getnamo/udp-ue4/blob/master/Source/UDPWrapper/Public/UDPComponent.h#L151) have optional parameters to overwrite IP/port values.

**Comment by satishkrr** [comment]
hi I mean is it possible in blueprint and not c++

**Comment by getnamo** [comment]
Yes those are blueprint functions, i was just referencing their call signatures which are defined in c++

**Comment by satishkrr** [comment]
Hi how i get the connection status like if the connection is established

**Comment by getnamo** [comment]
There is no such concept in UDP because it is by definition unreliable. You send information to an endpoint (IP) and socket (port) of your choice. Then _if_ that service on that other client/server received it and you want acknowledgement of receipt, the other service will need to send a reply of some sort, which _if_ it arrives back to your receiving socket of choice you can decode and do what you need.

If you want to have a connection type where you know connection states, consider using TCP (e.g. via https://github.com/getnamo/tcp-ue4) or a higher level communication protocol like websocket or socket.io (https://github.com/getnamo/socketio-client-ue4).

**Comment by satishkrr** [comment]
awesome, thanks brother
