### ISSUE TITLE
Unhandled Exception tcpservercomponent.cpp: Line 87

### ISSUE THREAD

**Issue by robotogre** [getnamo/udp-ue4#8]
> Unhandled exception
> 
> UE4Editor_TCPWrapper!<lambda_a8de54fa59a761fe631f44d43119327a>::operator()() [c:\users\robot\desktop\myproject\plugins\tcpwrapper\source\tcpwrapper\private\tcpservercomponent.cpp:87]
> UE4Editor_TCPWrapper!SetPromise<TUniqueFunction<void __cdecl(void)> &>() [c:\program files\epic games\ue_4.23\engine\source\runtime\core\public\async\async.h:49]
> UE4Editor_TCPWrapper!TAsyncRunnable<void>::Run() [c:\program files\epic games\ue_4.23\engine\source\runtime\core\public\async\async.h:404]
> UE4Editor_Core
> UE4Editor_Core
> kernel32
> ntdll

Here is the line in question:

`//Did we disconnect? Note that this almost never changed from connected due to engine bug, instead it will be caught when trying to send data
				ESocketConnectionState ConnectionState = Client->Socket->GetConnectionState();	`

**Comment by getnamo** [comment]
Looks like you meant to post this under https://github.com/getnamo/tcp-ue4/issues as it's related to that plugin: https://github.com/getnamo/tcp-ue4/blob/master/Source/TCPWrapper/Private/TCPServerComponent.cpp#L86

This particular issue might happen due to client or socket being removed on another thread whats the context for the bug?

**Comment by robotogre** [comment]
Oops! Yes, this is the wrong place. I've posted it in the correct project, and I have added more context.
